name: Canary Deployment

on:
  issue_comment:
    types: [created]

jobs:
  canary-deploy:
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, '/release-canary')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
            node-version: '20.x'
      
      - name: setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: setup pnpm and install dependencies
        uses: pnpm/action-setup@v3
        with:
            version: 9.1.1
            run_install: true

      - name: Publish to npm with canary tag
        run: pnpm run release:canary